{{- if .Values.podDisruptionBudget.api.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vooglaadija.fullname" . }}-api
  labels:
    {{- include "vooglaadija.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if .Values.podDisruptionBudget.api.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.api.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.api.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.api.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vooglaadija.apiSelectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if .Values.podDisruptionBudget.worker.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vooglaadija.fullname" . }}-worker
  labels:
    {{- include "vooglaadija.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if .Values.podDisruptionBudget.worker.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.worker.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.worker.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.worker.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vooglaadija.workerSelectorLabels" . | nindent 6 }}
{{- end }}
