{{- if .Values.api.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vooglaadija.fullname" . }}-api-storage
  labels:
    {{- include "vooglaadija.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
    - {{ .Values.api.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.api.persistence.size }}
  {{- if .Values.api.persistence.storageClass }}
  storageClassName: {{ .Values.api.persistence.storageClass }}
  {{- end }}
{{- end }}
---
{{- if .Values.worker.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vooglaadija.fullname" . }}-worker-storage
  labels:
    {{- include "vooglaadija.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  accessModes:
    - {{ .Values.worker.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.worker.persistence.size }}
  {{- if .Values.worker.persistence.storageClass }}
  storageClassName: {{ .Values.worker.persistence.storageClass }}
  {{- end }}
{{- end }}
