{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vooglaadija.fullname" . }}-secrets
  labels:
    {{- include "vooglaadija.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.db.password | b64enc | quote }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  secret-key: {{ .Values.api.secretKey | b64enc | quote }}
{{- end }}
