"""Regression tests for Story 2.4 web HTML consolidation."""

import ast
import re
from pathlib import Path
from unittest.mock import MagicMock

import pytest
from fastapi import Request
from slowapi.errors import RateLimitExceeded

from app.api.rate_limit_config import rate_limit_exceeded_handler

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _source(path: str) -> str:
    return (PROJECT_ROOT / path).read_text(encoding="utf-8")


def _python_function_definitions(name: str) -> list[Path]:
    definitions: list[Path] = []
    for path in (PROJECT_ROOT / "app").rglob("*.py"):
        if "__pycache__" in path.parts:
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == name:
                definitions.append(path.relative_to(PROJECT_ROOT))
    return definitions


def test_status_badge_html_has_one_first_party_generator():
    """Status badge HTML is generated by exactly one first-party Python helper."""
    assert _python_function_definitions("_status_badge_html") == [
        Path("app/api/routes/web_helpers.py")
    ]


def test_active_templates_and_dashboard_js_do_not_inline_status_badge_spans():
    """Active templates and dashboard.js do not hard-code status badge span markup."""
    checked_paths = [
        str(path.relative_to(PROJECT_ROOT))
        for path in sorted((PROJECT_ROOT / "app/templates").rglob("*.html"))
    ]
    checked_paths.append("app/static/js/dashboard.js")
    matches = [
        path
        for path in checked_paths
        if re.search(r"<span\s+class=[\"']status-badge", _source(path))
    ]

    assert matches == []


def test_dashboard_exposes_helper_generated_status_badge_templates_to_javascript():
    """The dashboard provides helper-generated badge template data for dashboard.js."""
    dashboard_template = _source("app/templates/dashboard.html")
    dashboard_js = _source("app/static/js/dashboard.js")

    assert 'id="status-badge-templates" type="application/json"' in dashboard_template
    assert "status_badge_templates_json()" in dashboard_template
    assert "document.getElementById('status-badge-templates')" in dashboard_js


def test_download_list_uses_canonical_row_partial():
    """The dashboard list delegates job rows to the canonical download item partial."""
    source = _source("app/templates/partials/_download_list.html")

    assert "partials/_download_item.html" in source
    assert 'class="download-row" data-job-id=' not in source


def test_web_fragment_helpers_are_defined_once_and_imported_by_web_routes():
    """Programmatic web fragment helpers live only in web_helpers and are reused by web routes."""
    assert _python_function_definitions("_error_html") == [Path("app/api/routes/web_helpers.py")]
    assert _python_function_definitions("_success_html") == [Path("app/api/routes/web_helpers.py")]

    web_source = (
        _source("app/api/routes/web/__init__.py")
        + _source("app/api/routes/web/web_auth.py")
        + _source("app/api/routes/web/web_downloads.py")
    )
    assert "from app.api.routes.web_helpers import" in web_source
    assert "_error_html" in web_source
    assert "_success_html" in web_source


def test_rate_limit_handler_reuses_centralized_error_fragment_helper():
    """The rate-limit handler delegates HTMX error-box HTML to web_helpers."""
    source = _source("app/api/rate_limit_config.py")

    assert "_rate_limit_error_html" in source
    assert 'class="error-box"' not in source
    assert "class='error-box'" not in source


def test_removed_story_2_1_partials_stay_absent_from_active_templates():
    """The removed Story 2.1 partial filenames are not reintroduced."""
    removed_partials = {"partials/_error" + ".html", "partials/_status" + "_badge.html"}
    matches: list[str] = []

    for path in (PROJECT_ROOT / "app/templates").rglob("*.html"):
        source = path.read_text(encoding="utf-8")
        for partial in removed_partials:
            if partial in source:
                matches.append(f"{path.relative_to(PROJECT_ROOT)}: {partial}")

    assert matches == []


def test_status_badge_helper_escapes_unknown_statuses():
    """Unknown status labels are escaped and receive CSS-safe status classes."""
    from app.api.routes.web_helpers import _status_badge_html

    badge = str(_status_badge_html("<script>alert(1)</script>"))

    assert "<script>" not in badge
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in badge
    assert 'class="status-badge status-script-alert-1-script"' in badge


def test_status_badge_css_defines_all_helper_known_statuses():
    """Stylesheets define every known status class emitted by the helper."""
    from app.api.routes.web_helpers import _STATUS_LABELS

    css_source = _source("frontend/css/src/styles.css")
    deployed_css = _source("app/static/css/styles.css")

    for status in _STATUS_LABELS:
        assert f".status-{status}" in css_source
        assert f".status-{status}" in deployed_css

    assert ".status-badge" in css_source
    assert ".status-badge" in deployed_css


@pytest.mark.asyncio
async def test_htmx_rate_limit_response_uses_centralized_html_fragment():
    """HTMX rate-limit responses keep Retry-After and return an error-box fragment."""
    mock_request = MagicMock(spec=Request)
    mock_request.headers = {"HX-Request": "true"}
    mock_exc = MagicMock(spec=RateLimitExceeded)
    mock_exc.detail = "5 per 1 minute"

    response = await rate_limit_exceeded_handler(mock_request, mock_exc)

    assert response.status_code == 429
    assert response.headers["Retry-After"] == "60"
    assert b'class="error-box"' in response.body
    assert b"Rate limit exceeded" in response.body
