"""Tests for Story 9.4 observability feature-flag default consistency."""

import re
from pathlib import Path

import pytest
import yaml

pytestmark = pytest.mark.slow


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OBSERVABILITY_FLAGS = ("FEATURE_METRICS_ENABLED", "FEATURE_TRACING_ENABLED")
DEPLOYMENT_HANDOFF_FILES = (
    ("deploy", "bootstrap.sh"),
    ("docs", "PRODUCTION_DEPLOYMENT.md"),
    (".github", "workflows", "docker.yml"),
)
DISABLED_OBSERVABILITY_DEFAULT_PATTERN = re.compile(
    r"\bFEATURE_(?:METRICS|TRACING)_ENABLED\b"
    r"(?:\s*[:=]\s*|:-)"
    r"[\"']?false[\"']?\b"
)


class ComposeLoader(yaml.SafeLoader):
    """YAML loader that tolerates Docker Compose extension tags."""


def _construct_compose_tag(loader: ComposeLoader, _tag_suffix: str, node: yaml.Node) -> object:
    if isinstance(node, yaml.SequenceNode):
        return loader.construct_sequence(node)
    if isinstance(node, yaml.MappingNode):
        return loader.construct_mapping(node)
    return loader.construct_scalar(node)


ComposeLoader.add_multi_constructor("!", _construct_compose_tag)


def _read_project_file(*parts: str) -> str:
    return PROJECT_ROOT.joinpath(*parts).read_text()


def _compose_config(filename: str) -> dict[str, object]:
    return yaml.load(_read_project_file(filename), Loader=ComposeLoader)


def _active_env_example_values() -> dict[str, str]:
    values: dict[str, str] = {}

    for raw_line in _read_project_file(".env.example").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", maxsplit=1)
        values[key.removeprefix("export ").strip()] = value.strip().strip("\"'")

    return values


def _bootstrap_generated_env_values() -> dict[str, str]:
    bootstrap = _read_project_file("deploy", "bootstrap.sh")
    match = re.search(
        r'"FEATURE_METRICS_ENABLED": "(?P<metrics>true|false)"'
        r'.*"FEATURE_TRACING_ENABLED": "(?P<tracing>true|false)"',
        bootstrap,
        flags=re.DOTALL,
    )
    assert match is not None, "bootstrap.sh generated env payload not found"

    return {
        "FEATURE_METRICS_ENABLED": match.group("metrics"),
        "FEATURE_TRACING_ENABLED": match.group("tracing"),
    }


def _assert_no_disabled_observability_defaults(content: str) -> None:
    assert DISABLED_OBSERVABILITY_DEFAULT_PATTERN.search(content) is None


@pytest.mark.unit
@pytest.mark.parametrize(
    "disabled_default",
    [
        "FEATURE_METRICS_ENABLED=false",
        "FEATURE_TRACING_ENABLED: false",
        "FEATURE_METRICS_ENABLED='false'",
        "${FEATURE_TRACING_ENABLED:-false}",
    ],
)
def test_disabled_observability_default_guard_catches_supported_forms(disabled_default: str):
    """The disabled-default guard should catch assignment and fallback syntaxes."""
    assert DISABLED_OBSERVABILITY_DEFAULT_PATTERN.search(disabled_default) is not None


@pytest.mark.unit
def test_compose_and_env_example_default_observability_flags_to_true():
    """The compose file and env template should agree on enabled observability defaults."""
    base_env = _compose_config("docker-compose.yml")["x-common-env"]
    env_example = _active_env_example_values()

    for flag in OBSERVABILITY_FLAGS:
        assert base_env[flag] == f"${{{flag}:-true}}"
        assert env_example[flag] == "true"


@pytest.mark.unit
def test_bootstrap_generated_env_defaults_observability_flags_to_true():
    """The production env generated by bootstrap.sh should enable observability by default."""
    bootstrap_env = _bootstrap_generated_env_values()

    for flag in OBSERVABILITY_FLAGS:
        assert bootstrap_env[flag] == "true"


@pytest.mark.unit
def test_bootstrap_no_longer_disables_observability_flags():
    """The bootstrap script should not retain stale disabled production defaults."""
    bootstrap = _read_project_file("deploy", "bootstrap.sh")

    assert "Observability (disabled for production)" not in bootstrap
    _assert_no_disabled_observability_defaults(bootstrap)


@pytest.mark.unit
def test_deployment_handoff_files_do_not_disable_observability_defaults():
    """Deployment handoff files should not introduce disabled observability defaults."""
    for path_parts in DEPLOYMENT_HANDOFF_FILES:
        _assert_no_disabled_observability_defaults(_read_project_file(*path_parts))
