services:
  certbot:
    image: certbot/dns-cloudflare
    volumes:
      - ./ssl:/etc/letsencrypt:rw
      - ./cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
    entrypoint: |
      /bin/sh -c '
        trap exit TERM;
        while :; do
          certbot renew \
            --dns-cloudflare \
            --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini \
            --dns-cloudflare-propagation-seconds 30 \
            --deploy-hook "sh -c \"touch /etc/letsencrypt/.nginx-reload-required\"" || true;
          sleep 12h;
        done;'
    restart: unless-stopped
