name: fast-forward

on:
  issue_comment:
    types: [created, edited]

jobs:
  fast-forward:
    if:
      ${{ contains(github.event.comment.body, '/fast-forward') && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          comment: 'on-error'
